name: Build Android AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }} # Your Infisical service token
      INFISICAL_PROJECT_ID: ${{ secrets.INFISICAL_PROJECT_ID }} # Project ID from Infisical
      INFISICAL_ENVIRONMENT: production # Change if needed

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Infisical CLI
      - name: Install Infisical CLI
        run: |
          curl -sSL https://github.com/Infisical/infisical/releases/latest/download/install.sh -o install.sh
          bash install.sh
          export PATH="$HOME/.infisical/bin:$PATH"
          infisical --version

      # 3. Pull secrets from Infisical
      - name: Pull secrets from Infisical
        run: |
          infisical export \
            --token $INFISICAL_TOKEN \
            --project-id $INFISICAL_PROJECT_ID \
            --environment $INFISICAL_ENVIRONMENT \
            --format dotenv \
            --output-file .env

      # 4. Load secrets
      - name: Load secrets
        run: |
          export $(grep -v '^#' .env | xargs)

      # 5. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 6. Cache Node modules
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      # 7. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 8. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 9. Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/build.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      # 10. Decode keystore (detect + convert PKCS12 → JKS)
      - name: Decode and prepare keystore
        run: |
          set -e
          mkdir -p android
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/key.bin

          if keytool -list -keystore android/key.bin -storetype PKCS12 -storepass "$ANDROID_KEYSTORE_PASSWORD" >/dev/null 2>&1; then
            echo "Detected PKCS12 keystore — converting to JKS..."
            keytool -importkeystore \
              -srckeystore android/key.bin -srcstoretype PKCS12 -srcstorepass "$ANDROID_KEYSTORE_PASSWORD" \
              -destkeystore android/my-release-key.jks -deststoretype JKS \
              -deststorepass "$ANDROID_KEYSTORE_PASSWORD" -destkeypass "$ANDROID_KEY_PASSWORD" \
              -srcalias "$ANDROID_KEY_ALIAS" -destalias "$ANDROID_KEY_ALIAS" -noprompt
          else
            echo "Not PKCS12 — assuming input is JKS bytes. Writing as JKS."
            mv android/key.bin android/my-release-key.jks
          fi

          ls -l android/
          echo "Keystore alias/entries:"
          keytool -list -v -keystore android/my-release-key.jks -storepass "$ANDROID_KEYSTORE_PASSWORD" || true

      # 11. Build AAB
      - name: Build AAB
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean bundleRelease \
            -Pandroid.injected.signing.store.file=my-release-key.jks \
            -Pandroid.injected.signing.store.password="$ANDROID_KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$ANDROID_KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$ANDROID_KEY_PASSWORD" \
            --stacktrace --info

      # 12. Upload artifact
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
