name: Build Android AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 5. Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 6. Fetch secrets from Infisical
      - name: Fetch secrets from Infisical
        uses: Infisical/secrets-action@v1.0.14
        with:
          method: 'universal'
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          domain: 'https://app.infisical.com' # use https://eu.infisical.com if EU region
          env-slug: dev
          project-slug: 'test-project-fzug'
          export-type: file
          file-output-path: /.env
          recursive: true
          include-imports: true
          secret-path: /

      # 7. Load env vars from .env
      - name: Load env from Infisical
        run: |
          FILE_PATH="$(pwd)/testproj.env"
          if [ -f "$FILE_PATH" ]; then
            echo "Loading $FILE_PATH"
            set -a
            source "$FILE_PATH"
            set +a
          else
            echo "Env file not found at $FILE_PATH"
            ls -lah
            exit 1
          fi

      # # 8. Decode and prepare keystore
      # - name: Decode and prepare keystore
      #   run: |
      #     mkdir -p android
      #     echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/key.bin

      #     if keytool -list -keystore android/key.bin -storetype PKCS12 -storepass "$ANDROID_KEYSTORE_PASSWORD" >/dev/null 2>&1; then
      #       echo "Detected PKCS12 keystore — converting to JKS..."
      #       keytool -importkeystore \
      #         -srckeystore android/key.bin -srcstoretype PKCS12 -srcstorepass "$ANDROID_KEYSTORE_PASSWORD" \
      #         -destkeystore android/my-release-key.jks -deststoretype JKS \
      #         -deststorepass "$ANDROID_KEYSTORE_PASSWORD" -destkeypass "$ANDROID_KEY_PASSWORD" \
      #         -srcalias "$ANDROID_KEY_ALIAS" -destalias "$ANDROID_KEY_ALIAS" -noprompt
      #     else
      #       echo "Not PKCS12 — assuming JKS."
      #       mv android/key.bin android/my-release-key.jks
      #     fi

      # # 9. Build AAB
      # - name: Build AAB
      #   run: |
      #     cd android
      #     chmod +x gradlew
      #     ./gradlew clean bundleRelease \
      #       -Pandroid.injected.signing.store.file=my-release-key.jks \
      #       -Pandroid.injected.signing.store.password="$ANDROID_KEYSTORE_PASSWORD" \
      #       -Pandroid.injected.signing.key.alias="$ANDROID_KEY_ALIAS" \
      #       -Pandroid.injected.signing.key.password="$ANDROID_KEY_PASSWORD" \
      #       --stacktrace --info
      # 8. Decode PKCS12 keystore (NO conversion)
      - name: Decode keystore
        run: |
          mkdir -p android
          printf "%s" "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/my-release-key.jks
          ls -lh android/my-release-key.jks
          echo "✅ Keystore decoded"




          # Debug keystore (optional, remove later)
          keytool -list -v \
            -keystore android/my-release-key.jks \
            -storepass "$ANDROID_KEYSTORE_PASSWORD" \
            -storetype PKCS12 | head -n 20
          echo "Keystore base64 length: ${#ANDROID_KEYSTORE_BASE64}"
          echo "$ANDROID_KEYSTORE_BASE64" | head -c 100

      # 9. Build AAB
      - name: Build AAB
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean bundleRelease \
            -Pandroid.injected.signing.store.file=my-release-key.jks \
            -Pandroid.injected.signing.store.password="$ANDROID_KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$ANDROID_KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$ANDROID_KEY_PASSWORD" \
            --stacktrace --info
      # 10. Upload AAB artifact
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab-${{ github.sha }}
          path: android/app/build/outputs/bundle/release/app-release.aab
