name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js (v20)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Set up JDK (required for Android)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4️⃣ Install npm dependencies
      - name: Install dependencies
        run: npm ci

      # 5️⃣ Decode Android Keystore from GitHub Secrets
      - name: Decode Android Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks

      # 6️⃣ Make gradlew executable (fix permission error)
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # 7️⃣ Build the signed release APK
      - name: Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=my-release-key.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}

      # 8️⃣ Upload APK as artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk
